# Generated by Django 3.0.5 on 2020-05-14 21:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_monitor_app', '0002_auto_20200414_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaytimeCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daytime_start', models.TimeField(default=datetime.time(7, 0, 0, 901711), help_text='HH:MM:SS 24-Hour Format')),
                ('daytime_end', models.TimeField(default=datetime.time(19, 0, 0, 901914), help_text='HH:MM:SS 24-Hour Format')),
            ],
        ),
        migrations.CreateModel(
            name='LightAccessory',
            fields=[
                ('device_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('device_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('max_temperature_day', models.FloatField(help_text='Temperature in fahrenheit')),
                ('min_temperature_day', models.FloatField(help_text='Temperature in fahrenheit')),
                ('max_temperature_night', models.FloatField(help_text='Temperature in fahrenheit')),
                ('min_temperature_night', models.FloatField(help_text='Temperature in fahrenheit')),
            ],
        ),
        migrations.AlterField(
            model_name='lightread',
            name='decice_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temperature_monitor_app.LightAccessory'),
        ),
        migrations.AlterField(
            model_name='temperatureread',
            name='device_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temperature_monitor_app.TemperatureSensor'),
        ),
        migrations.DeleteModel(
            name='LightSensors',
        ),
        migrations.DeleteModel(
            name='TemperatureSensors',
        ),
    ]
