# Generated by Django 3.0.6 on 2020-05-17 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_monitor_app', '0003_auto_20200514_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturesensor',
            name='sensor_type',
            field=models.IntegerField(choices=[(11, 'DHT11'), (22, 'DHT22')], default=11),
        ),
        migrations.AlterField(
            model_name='daytimecycle',
            name='daytime_end',
            field=models.TimeField(default=datetime.time(19, 0, 0, 472849), help_text='HH:MM:SS 24-Hour Format'),
        ),
        migrations.AlterField(
            model_name='daytimecycle',
            name='daytime_start',
            field=models.TimeField(default=datetime.time(7, 0, 0, 472588), help_text='HH:MM:SS 24-Hour Format'),
        ),
    ]
