# Generated by Django 3.0.6 on 2020-05-17 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_monitor_app', '0008_auto_20200517_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytimecycle',
            name='daytime_end',
            field=models.TimeField(default=datetime.time(19, 0, 0, 753523), help_text='HH:MM:SS 24-Hour Format'),
        ),
        migrations.AlterField(
            model_name='daytimecycle',
            name='daytime_start',
            field=models.TimeField(default=datetime.time(7, 0, 0, 753308), help_text='HH:MM:SS 24-Hour Format'),
        ),
    ]
