# Generated by Django 3.0.5 on 2020-07-09 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_monitor_app', '0009_auto_20200517_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytimecycle',
            name='daytime_end',
            field=models.TimeField(default=datetime.time(19, 0, 0, 282130), help_text='HH:MM:SS 24-Hour Format'),
        ),
        migrations.AlterField(
            model_name='daytimecycle',
            name='daytime_start',
            field=models.TimeField(default=datetime.time(7, 0, 0, 282101), help_text='HH:MM:SS 24-Hour Format'),
        ),
    ]
