version: '3.3'
services:
  pg:
    image: postgres:12.1-alpine
    container_name: "khalo_db"
    ports:
      - ${PORT_TRANSLATION}
    volumes:
      - /home/todoroki/khalitos_way/database/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
      PGDATA: /var/lib/postgresql/data
