# Generated by Django 3.0.5 on 2020-04-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightread',
            name='sample_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lightsensors',
            name='turn_on_end',
            field=models.TimeField(help_text='HH:MM:SS 24-Hour Format'),
        ),
        migrations.AlterField(
            model_name='lightsensors',
            name='turn_on_start',
            field=models.TimeField(help_text='HH:MM:SS 24-Hour Format'),
        ),
        migrations.AlterField(
            model_name='temperatureread',
            name='sample_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='temperaturesensors',
            name='max_temperature',
            field=models.FloatField(help_text='Temperature in fahrenheit'),
        ),
        migrations.AlterField(
            model_name='temperaturesensors',
            name='min_temperature',
            field=models.FloatField(help_text='Temperature in fahrenheit'),
        ),
    ]
